---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


This is a line from R studio

12.1 Already Completed. (Pre Req)
12.2 Created new Repo Successfully. At first had trouble getting more than one person on a team but was quickly resolved.
12.3 Easy to follow directions, linked successfully.
12.4 Having some problems with commiting the file. Running into the error message "Author identity unknown."
12.5 Simply back of the commit screen and press the push button
12.6 Go back to github to see commits that were made

Lab 1 Experiences:
12.1: Done previously
12.2: Done Previously
12.3: Followed the steps given to link the RStudio with the GitHub repository
12.4: 12.4 Having some problems with commiting the file. Running into the error message "Author identity unknown.". We then had to update our username and email on the RStudio for GitHub
12.5: We closed out of the commit section and pushed to the main GitHub
12.6: Go back and refresh GitHub to make sure everything worked
